# Generated by Django 5.1.2 on 2024-11-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("country", models.CharField(max_length=50)),
                ("main_image", models.ImageField(upload_to="uploads/")),
                ("main_description", models.TextField(blank=True, null=True)),
                ("h1_title", models.CharField(max_length=70)),
                ("h1_image", models.ImageField(upload_to="uploads/")),
                ("h2_title", models.CharField(max_length=70)),
                ("h2_description", models.CharField(max_length=200)),
                ("h2_image", models.ImageField(upload_to="uploads/")),
                ("h3_title", models.CharField(max_length=70)),
                ("h3_description", models.CharField(max_length=200)),
                ("h3_image", models.ImageField(upload_to="uploads/")),
                (
                    "categories",
                    models.ManyToManyField(related_name="posts", to="blog.category"),
                ),
            ],
        ),
    ]
