# Generated by Django 5.1.2 on 2024-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="h1_image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="h2_image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="h3_image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="main_image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
