# Generated by Django 5.1.2 on 2024-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_h1_image_alter_post_h2_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="h1_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="h2_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="h3_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
