# Generated by Django 5.1.2 on 2024-11-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_h1_image_alter_post_h2_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="h1_image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="h1_title",
        ),
        migrations.RemoveField(
            model_name="post",
            name="h2_description",
        ),
        migrations.RemoveField(
            model_name="post",
            name="h2_image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="h2_title",
        ),
        migrations.RemoveField(
            model_name="post",
            name="h3_description",
        ),
        migrations.RemoveField(
            model_name="post",
            name="h3_image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="h3_title",
        ),
        migrations.RemoveField(
            model_name="post",
            name="main_description",
        ),
        migrations.AddField(
            model_name="post",
            name="first_text",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="five_text",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="fourth_text",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="second_text",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="third_text",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
