# Generated by Django 5.1.2 on 2024-11-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_remove_post_h1_image_remove_post_h1_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="five_text",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
