# Generated by Django 5.1.2 on 2024-10-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=10)),
                ("date_tour", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="uploads/")),
                ("description", models.TextField(blank=True, null=True)),
                ("done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
